### ISSUE TITLE
Use `sed` instead of `ANIMATE_REGRESSION_TEST`

### ISSUE THREAD

**Issue by jwallwork23** [mesh-adaptation/animate#111]
Rather than confusing the demo content with environment variables, we should apply specific modifications with `sed` when running the test suite.

**Comment by ddundo** [comment]
Just so I don't step on your toes too much, can I take this and #110 as well, and do what I did in goalie? :)

**Comment by jwallwork23** [comment]
> Just so I don't step on your toes too much, can I take this and #110 as well, and do what I did in goalie? :)

Honestly it's fine - take any issue you like! I only assign things to myself as a reminder to work on them.
