### ISSUE TITLE
Metric advection demo

### ISSUE THREAD

**Issue by ddundo** [mesh-adaptation/animate#144]
I've done the bubble shear test case with metric advection - would it be useful to put it up as a demo? I don't know how niche this is :)

**Comment by jwallwork23** [comment]
Sure, go for it!

**Comment by ddundo** [comment]
@jwallwork23 could you please tell me how you computed the "relative L2 error" in the bubble shear section in your thesis? I'm thinking what would be the best way to interpolate the fields such that they're on the same mesh - i.e. interpolate the final solution or the initial one onto the other one's mesh, or interpolate both of them on a fine resolution uniform mesh?

I'm also curious how you computed the _relative_ error considering there are 0 values of the concentration field. I don't know if there's a more elegant way to do it than just manually handling those :)

**Comment by jwallwork23** [comment]
https://github.com/jwallwork23/adapt_utils/blob/master/unsteady/test_cases/bubble_shear/run_adapt.py

Here’s the code. It appears I redefined the initial condition on the final mesh. I think the relative error is meant as a quotient of spatial integrals, rather than pointwise? (I don’t have the thesis open- am on the train.)

**Comment by ddundo** [comment]
Ah sorry, I should have thought myself to look at the code :) thanks for this!

**Comment by karimnorouzi** [comment]
Hi, I am interested in this demo. where can I find the files ? 

----------------------------------------

From: "Davor Dundovic" ***@***.***>
Sent: 7/26/24 12:26 PM
To: mesh-adaptation/animate ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mesh-adaptation/animate] Metric advection demo (Issue #144)

I've done the bubble shear test case with metric advection - would it be useful to put it up as a demo? I don't know how niche this is :)

**Comment by ddundo** [comment]
Hi @karimnorouzi, the PR is under review at the moment (https://github.com/mesh-adaptation/animate/pull/145) so you can look there. It will likely get merged within the next week
