### ISSUE TITLE
Parallel tests fail

### ISSUE THREAD

**Issue by ddundo** [mesh-adaptation/animate#151]
See https://github.com/mesh-adaptation/animate/actions/runs/11310604427

**Comment by jwallwork23** [comment]
Was that on a branch or `main`? The latest scheduled job passed fine: https://github.com/mesh-adaptation/animate/actions/runs/11422611991.

**Comment by jwallwork23** [comment]
Nevermind, I figured out how to check - it's `main`. Re-running now.

**Comment by jwallwork23** [comment]
Okay tests now pass: https://github.com/mesh-adaptation/animate/actions/runs/11310604427/job/31787257742.

I'll close this issue but we can reopen it if the issue reoccurs.
