### ISSUE TITLE
Improvements to bubble shear demo

### ISSUE THREAD

**Issue by ddundo** [mesh-adaptation/animate#153]
![image](https://github.com/user-attachments/assets/ea802c22-5010-448f-b9e7-8c09b9850893)

- [x] Vast majority of effort in the bubble shear demo goes into interpolating velocity `u.interpolate(velocity_expression(mesh, t))`
  - The reason is that `t` in `velocity_expression` is hardcoded as a `float` so a lot of time is spent recompiling it. Instead, it should be wrapped in `Constant` (or `Function` of R). This made it much faster. 
  - Doing `u.dat.data[:] = u_numpy`, where `u_numpy` is the velocity computed with `numpy` also works and is actually faster than the above, but it's not very firedrake-y, so I went with the above method
- [x] The first computed metric in metric advection should be normalised I think
- [x] Wrong description in Line 416
- [x] Mention explicit timestepping and CFL condition in the exercise rubric
- [ ] Recompute initial condition on the first adapted mesh, rather than projecting the one computed on the uniform mesh. This may actually give a slightly higher error in the end - put it in the exercise rubric?

**Comment by jwallwork23** [comment]
Thanks for looking into this! I also found there's plenty of optimisation to be done across the repos.
