### ISSUE TITLE
Hessian metric demo

### ISSUE THREAD

**Issue by jwallwork23** [mesh-adaptation/animate#53]
Building on the previous demo, this one should create a metric by recovering a Hessian.

**Comment by jwallwork23** [comment]
Perhaps compute the Hessian of a sensor function and show the results of different normalisation orders. Could also compare averaging vs intersection?

**Comment by stephankramer** [comment]
Started writing a Hessian demo. @acse-ej321 may add a more applied one later

**Comment by jwallwork23** [comment]
Closed by #145
