### ISSUE TITLE
Issue building Docker container on GitHub Actions

### ISSUE THREAD

**Issue by jwallwork23** [mesh-adaptation/animate#79]
Building the Docker container locally seems fine. However, the weekly build on the CI platform has given the same error for the past two weeks:
```
142.2 *********************************************************************************************
142.2            UNABLE to CONFIGURE with GIVEN OPTIONS (see configure.log for details):
142.2 ---------------------------------------------------------------------------------------------
142.2               --with-suitesparse-dir=/home/firedrake/petsc/packages did not work
142.2 *********************************************************************************************
```
Worth investigating.

**Comment by ddundo** [comment]
Lazy temporary solution: I rebuilt the image with `FROM firedrakeproject/firedrake-vanilla:2024-02
` and then all https://github.com/pyroteus/goalie/pull/128 tests pass (and your mfe.py example works).

**Comment by jwallwork23** [comment]
@ddundo would you mind opening a PR with this temporary fix? Don't close this issue, though.

It should be `firedrake-parmmg`. If you could update the install scripts in the PR too that'd be great, thanks.

**Comment by ddundo** [comment]
Thanks @jwallwork23, please see #91. I actually also had to remove the Thetis install that you recently added. With it, 
```
RUN bash -c "source firedrake/bin/activate; \
    cd firedrake/src/firedrake; \
    firedrake-update --install thetis"
```
returns
```
# everything looks fine ...
Successfully updated Firedrake.

Removing cached TSFC kernels from /home/firedrake/firedrake/.cache/tsfc
Cache directory could not be found
[0]PETSC ERROR:------------------------------------------------------------------------
[0]PETSC ERROR: Caught signal
[0]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[0]PETSC ERROR:or see https://petsc.org/release/faq/#valgrind and https://petsc.org/release/faq/
[0]PETSC ERROR: configure using --with-debugging=yes, recompile, link, and run
[0]PETSC ERROR:to get more information on the crash.
application called MPI_Abort(MPI_COMM_WORLD, 59) - process 0
[unset]: PMIU_write error; fd=-1 buf=:cmd=abort exitcode=59 message=application called MPI_Abort(MPI_COMM_WORLD, 59) - process 0
:
system msg for write_line failure : Bad file descriptor
```
I did not investigate this since it's a temporary fix anyway.

So in summary: reverting `firedrakeproject/firedrake-vanilla:2024-02` and not installing Thetis works. I tried `firedrakeproject/firedrake-vanilla:latest` without Thetis which again gives the error in your original comment here. (@acse-ej321 this Thetis change may affect you I think?)

**Comment by acse-ej321** [comment]
@ddundo @jwallwork23 - I have managed to get a separate singularity container working which includes Thetis and a couple other libraries I am using, so the reversion is not a limitation for me currently. It would be nice to use the docker image in the future though as it is much more efficient from which to load.

**Comment by jwallwork23** [comment]
The Docker build is working fine now.
