### ISSUE TITLE
Avoid interpolation deprecation warning

### ISSUE THREAD

**Issue by ddundo** [mesh-adaptation/animate#81]
Do the same in animate as in https://github.com/pyroteus/goalie/issues/105

**Comment by ddundo** [comment]
Actually @jwallwork23, would you mind taking this please? I don't mind doing it but I don't see a pretty way of avoiding `self.interpolate(...)` in metric.py

**Comment by jwallwork23** [comment]
Sure, no worries.

**Comment by acse-ej321** [comment]
@jwallwork23 - would you mind if I took this? I have found most the instances locally already.
