### ISSUE TITLE
Install Thetis in the Docker container

### ISSUE THREAD

**Issue by jwallwork23** [mesh-adaptation/animate#82]
No big deal to include Thetis and it would be useful, especially when working on Goalie-Thetis compatibility.

**Comment by jwallwork23** [comment]
Note https://github.com/pyroteus/goalie/wiki/Running-on-HPC.

**Comment by ddundo** [comment]
Reopening since I had to revert this in #91. See discussion in issue #79.

**Comment by ddundo** [comment]
@jwallwork23 did you try installing Thetis with the updated build?

**Comment by jwallwork23** [comment]
> @jwallwork23 did you try installing Thetis with the updated build?

I hadn't, but thanks for the suggestion. Looks good: https://github.com/mesh-adaptation/mesh-adaptation-docs/pull/31.
