### ISSUE TITLE
Parallel Hessian tests fail locally

### ISSUE THREAD

**Issue by jwallwork23** [mesh-adaptation/animate#92]
I have two tests failing locally, even on `main`:
```
test/test_parallel.py::test_hessian_bowl_np2[2]
test/test_parallel.py::test_hessian_bowl_np2[3]
```
The error messages are assertion errors for the metric against its expected value.

**Comment by stephankramer** [comment]
Yeah, just looking into this. This is all a bit weird: it appears that if in _compute_gradient_and_hessian you *don't* integrate by parts you get the right answer. I really don't understand why tbh, it looks all correct to me (IBP or not should be exactly the same in this case).

**Comment by stephankramer** [comment]
So I managed to produce the following MFE:
```
from firedrake import *

mesh = UnitSquareMesh(2, 2)
x, y = SpatialCoordinate(mesh)
V = VectorFunctionSpace(mesh, "CG", 1)
W = FunctionSpace(mesh, "CG", 1)
field = Function(W).interpolate(x)
g = TrialFunction(V)
phi = TestFunction(V)
sol = Function(V)
n = FacetNormal(mesh)

a = (
    inner(phi, g) * dx
)
L = (
    field * dot(phi, n) * ds
    - field * div(phi) * dx
)
solve(a == L, sol)
print(sol.dat.data)
```
which gives the expected result in serial (i.e. sol = (1,0)) but rubbish in parallel.
Could you sanity check the above and confirm you think this is a firedrake bug?

**Comment by jwallwork23** [comment]
Thanks for looking into this @stephankramer. Yeah I can't see why your example would fail. The tests were passing locally for me previously and that part of the code hasn't changed so I would be inclined to think this cropped up last time I ran `firedrake-update`.

**Comment by stephankramer** [comment]
Hm so it works correctly in the firedrakeproject/firedrake:latest container (the MFE that is).

**Comment by jwallwork23** [comment]
Oh yeah sorry I should mention that it passes fine on the CI, just fails for me locally.

**Comment by ddundo** [comment]
The mfe and the tests pass locally for me as well (using the new docker image from https://github.com/pyroteus/animate/commit/b1a0acf4ce19ec899660662de5233f0330a1f79f) :)
